import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jul 8, 2020, 1:38:00 PM
 */

/**
 *
 * @author Lenovo
 */
public class NewJFrame extends javax.swing.JFrame {
    DefaultTableModel tm = null;
    Connection con=null;
    Statement stmt =null;
    Connection con1=null;
    Statement stmt1 =null;
    ResultSet rs=null;
    String uid = null;
    String userToView = null;
    int amount=0;
    int a=0;
    int pa=0;
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    private String CURDATE() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    private String curdate() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DASHBOARD = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        CARRENT = new javax.swing.JButton();
        OFFFERS = new javax.swing.JButton();
        END = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        REGISTER = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        userTF1 = new javax.swing.JTextField();
        cont = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        PF1 = new javax.swing.JPasswordField();
        jLabel37 = new javax.swing.JLabel();
        RENT = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cars = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rateLabel = new javax.swing.JTextField();
        drivercheckbox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JTextField();
        guideLabel = new javax.swing.JTextField();
        finaltotalLabel = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        disLabel = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        SPECIAL = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        PROFILE = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        car = new javax.swing.JTextField();
        bookdate = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        FINAL = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AMOUNTLABEL = new javax.swing.JTextField();
        DATE = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        PASSWORDLABEL = new javax.swing.JPasswordField();
        RETURN = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ABOUTUS = new javax.swing.JFrame();
        jLabel35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTF2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PF2 = new javax.swing.JPasswordField();

        DASHBOARD.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DASHBOARD.setMinimumSize(new java.awt.Dimension(1300, 700));
        DASHBOARD.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel4.setText("WELCOME TO YOUR DASHBOARD");
        DASHBOARD.getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 0, 2210, 130);

        CARRENT.setFont(new java.awt.Font("Segoe Script", 1, 24));
        CARRENT.setText("RENT A CAR");
        CARRENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARRENTActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(CARRENT);
        CARRENT.setBounds(930, 180, 270, 49);

        OFFFERS.setFont(new java.awt.Font("Segoe Script", 1, 24));
        OFFFERS.setText("SPECIAL OFFERS");
        OFFFERS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFFERSActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(OFFFERS);
        OFFFERS.setBounds(930, 240, 270, 49);

        END.setFont(new java.awt.Font("Segoe Script", 1, 24));
        END.setText("END RIDE");
        END.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENDActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(END);
        END.setBounds(930, 300, 270, 49);

        jButton6.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jButton6.setText("MY PROFILE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(jButton6);
        jButton6.setBounds(930, 360, 270, 49);

        jButton7.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jButton7.setText("MORE ABOUT US");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(jButton7);
        jButton7.setBounds(930, 430, 270, 49);

        jButton8.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jButton8.setText("HISTORY");
        DASHBOARD.getContentPane().add(jButton8);
        jButton8.setBounds(830, 540, 160, 49);

        jButton9.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jButton9.setText("LOGOUT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        DASHBOARD.getContentPane().add(jButton9);
        jButton9.setBounds(1140, 540, 150, 50);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/34.jpg"))); // NOI18N
        jLabel36.setText("jLabel36");
        DASHBOARD.getContentPane().add(jLabel36);
        jLabel36.setBounds(-870, -10, 2180, 690);

        REGISTER.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        REGISTER.setMinimumSize(new java.awt.Dimension(800, 600));
        REGISTER.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel12.setText("CREATE A NEW ACCOUNT");
        REGISTER.getContentPane().add(jLabel12);
        jLabel12.setBounds(20, -20, 1020, 140);

        jLabel13.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel13.setText("SELECT A USERNAME");
        REGISTER.getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 140, 320, 40);

        jLabel14.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel14.setText("NAME");
        REGISTER.getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 200, 160, 40);

        jLabel15.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel15.setText("CONTACT NO.");
        REGISTER.getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 270, 184, 40);

        jLabel16.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel16.setText("ADDRESS");
        REGISTER.getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 330, 131, 40);

        jLabel17.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel17.setText("PASSWORD");
        REGISTER.getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 400, 154, 40);

        jButton11.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jButton11.setText("CREATE ACCOUNT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        REGISTER.getContentPane().add(jButton11);
        jButton11.setBounds(150, 490, 290, 49);

        nameTF.setFont(new java.awt.Font("Segoe Script", 1, 24));
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        REGISTER.getContentPane().add(nameTF);
        nameTF.setBounds(390, 210, 180, 30);

        userTF1.setFont(new java.awt.Font("Segoe Script", 1, 24));
        userTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF1ActionPerformed(evt);
            }
        });
        REGISTER.getContentPane().add(userTF1);
        userTF1.setBounds(390, 150, 180, 30);

        cont.setFont(new java.awt.Font("Segoe Script", 1, 24));
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });
        REGISTER.getContentPane().add(cont);
        cont.setBounds(390, 270, 180, 30);

        add.setFont(new java.awt.Font("Segoe Script", 1, 24));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        REGISTER.getContentPane().add(add);
        add.setBounds(390, 330, 180, 30);

        PF1.setFont(new java.awt.Font("Segoe Script", 1, 24));
        REGISTER.getContentPane().add(PF1);
        PF1.setBounds(390, 400, 180, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/123.jpg"))); // NOI18N
        jLabel37.setText("jLabel37");
        REGISTER.getContentPane().add(jLabel37);
        jLabel37.setBounds(-370, -150, 1750, 780);

        RENT.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        RENT.setMinimumSize(new java.awt.Dimension(800, 700));
        RENT.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                RENTWindowActivated(evt);
            }
        });
        RENT.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel5.setText("RENT A CAR");
        RENT.getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 10, 490, 70);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel6.setText("SELECT A CAR");
        RENT.getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 100, 156, 29);

        cars.setFont(new java.awt.Font("Consolas", 1, 24));
        cars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));
        RENT.getContentPane().add(cars);
        cars.setBounds(220, 100, 150, 30);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel7.setText("DAYS CAR REQUIRED");
        RENT.getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 250, 29);

        jTextField1.setFont(new java.awt.Font("Consolas", 1, 24));
        RENT.getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 210, 130, 35);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel8.setText("RATE PER DAY");
        RENT.getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 160, 156, 29);

        rateLabel.setFont(new java.awt.Font("Consolas", 1, 24));
        RENT.getContentPane().add(rateLabel);
        rateLabel.setBounds(320, 150, 130, 35);

        drivercheckbox.setFont(new java.awt.Font("Consolas", 1, 24));
        drivercheckbox.setText("DRIVER NEEDED");
        RENT.getContentPane().add(drivercheckbox);
        drivercheckbox.setBounds(550, 100, 195, 37);

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel9.setText("CAR CHARGES");
        RENT.getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 320, 143, 29);

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel10.setText("GUIDE CHARGES");
        RENT.getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 370, 180, 30);

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel11.setText("TOTAL ");
        RENT.getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 430, 78, 29);

        totalLabel.setFont(new java.awt.Font("Consolas", 1, 24));
        RENT.getContentPane().add(totalLabel);
        totalLabel.setBounds(320, 310, 130, 35);

        guideLabel.setFont(new java.awt.Font("Consolas", 1, 24));
        RENT.getContentPane().add(guideLabel);
        guideLabel.setBounds(320, 370, 130, 35);

        finaltotalLabel.setFont(new java.awt.Font("Consolas", 1, 24));
        finaltotalLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finaltotalLabelActionPerformed(evt);
            }
        });
        RENT.getContentPane().add(finaltotalLabel);
        finaltotalLabel.setBounds(320, 430, 130, 35);

        jButton3.setFont(new java.awt.Font("Cambria", 0, 24));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        RENT.getContentPane().add(jButton3);
        jButton3.setBounds(240, 550, 103, 37);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 24));
        jButton4.setText("CALCULATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        RENT.getContentPane().add(jButton4);
        jButton4.setBounds(220, 600, 163, 37);

        jButton5.setFont(new java.awt.Font("Cambria", 1, 24));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        RENT.getContentPane().add(jButton5);
        jButton5.setBounds(0, 0, 95, 37);

        jButton10.setFont(new java.awt.Font("Cambria", 1, 24));
        jButton10.setText("CONTINUE..");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        RENT.getContentPane().add(jButton10);
        jButton10.setBounds(713, 613, 170, 40);

        jLabel33.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel33.setText("DISCOUNT");
        RENT.getContentPane().add(jLabel33);
        jLabel33.setBounds(110, 500, 104, 29);

        disLabel.setFont(new java.awt.Font("Consolas", 1, 24));
        RENT.getContentPane().add(disLabel);
        disLabel.setBounds(320, 490, 130, 35);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/danielle-macinnes-IuLgi9PWETU-unsplash.jpg"))); // NOI18N
        jLabel43.setText("jLabel43");
        RENT.getContentPane().add(jLabel43);
        jLabel43.setBounds(-890, -590, 1950, 1250);

        SPECIAL.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        SPECIAL.setMinimumSize(new java.awt.Dimension(800, 700));
        SPECIAL.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SPECIALWindowActivated(evt);
            }
        });
        SPECIAL.getContentPane().setLayout(null);

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel31.setText("SPECIAL OFFERS");
        SPECIAL.getContentPane().add(jLabel31);
        jLabel31.setBounds(150, 10, 640, 70);

        jLabel32.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel32.setText("TYPE THE CODE");
        SPECIAL.getContentPane().add(jLabel32);
        jLabel32.setBounds(140, 150, 221, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        SPECIAL.getContentPane().add(jTextField3);
        jTextField3.setBounds(400, 160, 210, 20);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "DESCRIPTION", "DISCOUNT"
            }
        ));
        table1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(table1);
        table1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        SPECIAL.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 360, 640, 140);

        jButton15.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24));
        jButton15.setText("CONTINUE..");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        SPECIAL.getContentPane().add(jButton15);
        jButton15.setBounds(300, 210, 190, 47);

        jLabel34.setFont(new java.awt.Font("Segoe Script", 1, 24));
        jLabel34.setText("TRENDING OFFERS");
        SPECIAL.getContentPane().add(jLabel34);
        jLabel34.setBounds(240, 310, 270, 30);

        jButton18.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24));
        jButton18.setText("SHOW OFFERS");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        SPECIAL.getContentPane().add(jButton18);
        jButton18.setBounds(300, 520, 210, 50);

        jButton19.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24));
        jButton19.setText("BACK");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        SPECIAL.getContentPane().add(jButton19);
        jButton19.setBounds(10, 10, 100, 40);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1196598.jpg"))); // NOI18N
        jLabel39.setText("jLabel39");
        SPECIAL.getContentPane().add(jLabel39);
        jLabel39.setBounds(-220, -110, 1180, 750);

        PROFILE.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        PROFILE.setMinimumSize(new java.awt.Dimension(800, 700));
        PROFILE.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                PROFILEWindowActivated(evt);
            }
        });
        PROFILE.getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel23.setText("MY PROFILE");
        PROFILE.getContentPane().add(jLabel23);
        jLabel23.setBounds(150, 30, 570, 80);

        jLabel24.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel24.setText("NAME");
        PROFILE.getContentPane().add(jLabel24);
        jLabel24.setBounds(120, 190, 90, 20);

        jLabel25.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel25.setText("USERNAME");
        PROFILE.getContentPane().add(jLabel25);
        jLabel25.setBounds(100, 130, 144, 44);

        jLabel26.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel26.setText("ADDRESS");
        PROFILE.getContentPane().add(jLabel26);
        jLabel26.setBounds(100, 240, 120, 44);

        jLabel27.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel27.setText("CONTACT NO.");
        PROFILE.getContentPane().add(jLabel27);
        jLabel27.setBounds(80, 310, 177, 44);

        jLabel28.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel28.setText("CAR TAKEN");
        PROFILE.getContentPane().add(jLabel28);
        jLabel28.setBounds(100, 370, 151, 44);

        jLabel29.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel29.setText("       BOOKED DATE");
        PROFILE.getContentPane().add(jLabel29);
        jLabel29.setBounds(10, 430, 259, 44);

        jLabel30.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jLabel30.setText("PASSWORD");
        PROFILE.getContentPane().add(jLabel30);
        jLabel30.setBounds(90, 500, 145, 44);

        jButton14.setFont(new java.awt.Font("Segoe Print", 1, 24));
        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        PROFILE.getContentPane().add(jButton14);
        jButton14.setBounds(10, 10, 110, 40);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 140, 160, 30);

        uname.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(uname);
        uname.setBounds(350, 190, 160, 30);

        address.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(address);
        address.setBounds(350, 250, 160, 30);

        contact.setFont(new java.awt.Font("Segoe Print", 1, 24));
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        PROFILE.getContentPane().add(contact);
        contact.setBounds(350, 310, 160, 30);

        car.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(car);
        car.setBounds(350, 380, 160, 30);

        bookdate.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(bookdate);
        bookdate.setBounds(350, 440, 160, 30);

        pass.setFont(new java.awt.Font("Segoe Print", 1, 24));
        PROFILE.getContentPane().add(pass);
        pass.setBounds(350, 510, 160, 30);

        jButton12.setText("...");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        PROFILE.getContentPane().add(jButton12);
        jButton12.setBounds(520, 190, 40, 30);

        jButton16.setText("...");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        PROFILE.getContentPane().add(jButton16);
        jButton16.setBounds(520, 250, 40, 30);

        jButton17.setText("...");
        PROFILE.getContentPane().add(jButton17);
        jButton17.setBounds(520, 310, 40, 23);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wp3051771-mickey-mouse-hd-wallpapers.jpg"))); // NOI18N
        jLabel40.setText("jLabel40");
        PROFILE.getContentPane().add(jLabel40);
        jLabel40.setBounds(-690, 10, 1700, 840);

        FINAL.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FINAL.setBackground(new java.awt.Color(255, 255, 255));
        FINAL.setMinimumSize(new java.awt.Dimension(800, 700));
        FINAL.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                FINALWindowActivated(evt);
            }
        });
        FINAL.getContentPane().setLayout(null);

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 73));
        jLabel18.setText("RETURN CAR");
        FINAL.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 30, 640, 150);

        jLabel19.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel19.setText("AMOUNT DUE");
        FINAL.getContentPane().add(jLabel19);
        jLabel19.setBounds(46, 220, 140, 29);

        jLabel20.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel20.setText("BOOKING DATE");
        FINAL.getContentPane().add(jLabel20);
        jLabel20.setBounds(50, 280, 156, 29);

        AMOUNTLABEL.setFont(new java.awt.Font("Consolas", 1, 24));
        FINAL.getContentPane().add(AMOUNTLABEL);
        AMOUNTLABEL.setBounds(250, 210, 160, 35);

        DATE.setFont(new java.awt.Font("Consolas", 1, 24));
        FINAL.getContentPane().add(DATE);
        DATE.setBounds(250, 270, 160, 35);

        jLabel21.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel21.setText("LOGIN ID(OFFICIALS ONLY)");
        FINAL.getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 410, 312, 29);

        jLabel22.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel22.setText("PASSWORD");
        FINAL.getContentPane().add(jLabel22);
        jLabel22.setBounds(130, 490, 104, 29);

        jTextField4.setFont(new java.awt.Font("Consolas", 1, 24));
        FINAL.getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 410, 160, 35);

        PASSWORDLABEL.setFont(new java.awt.Font("Consolas", 1, 24));
        FINAL.getContentPane().add(PASSWORDLABEL);
        PASSWORDLABEL.setBounds(400, 480, 160, 35);

        RETURN.setFont(new java.awt.Font("Consolas", 1, 24));
        RETURN.setText("RETURN CAR");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });
        FINAL.getContentPane().add(RETURN);
        RETURN.setBounds(210, 580, 190, 40);

        jButton13.setFont(new java.awt.Font("Consolas", 1, 24));
        jButton13.setText("BACK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        FINAL.getContentPane().add(jButton13);
        jButton13.setBounds(10, 10, 85, 37);

        jLabel41.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel41.setText("OFFICIAL WORK");
        FINAL.getContentPane().add(jLabel41);
        jLabel41.setBounds(260, 340, 180, 30);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/123.jpg"))); // NOI18N
        jLabel38.setText("jLabel38");
        FINAL.getContentPane().add(jLabel38);
        jLabel38.setBounds(-550, 0, 1670, 660);

        ABOUTUS.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ABOUTUS.setMinimumSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout ABOUTUSLayout = new javax.swing.GroupLayout(ABOUTUS.getContentPane());
        ABOUTUS.getContentPane().setLayout(ABOUTUSLayout);
        ABOUTUSLayout.setHorizontalGroup(
            ABOUTUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ABOUTUSLayout.setVerticalGroup(
            ABOUTUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1196598.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 72));
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("APNI CAR RENTALS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 810, 70);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 48));
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 210, 40);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 48));
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 290, 220, 57);

        userTF2.setFont(new java.awt.Font("Cambria Math", 1, 36));
        userTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF2ActionPerformed(evt);
            }
        });
        getContentPane().add(userTF2);
        userTF2.setBounds(270, 190, 240, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 36));
        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 410, 230, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 36));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 490, 230, 60);

        PF2.setFont(new java.awt.Font("Arial Black", 1, 36));
        PF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF2ActionPerformed(evt);
            }
        });
        getContentPane().add(PF2);
        PF2.setBounds(270, 300, 240, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     uid = userTF2.getText();
    String pwd = new String(PF2.getPassword());
      try{
    con =    DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt =  (Statement) con.createStatement();
    String sql = "SELECT Pass FROM User WHERE uname= '" + uid + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    String pass = rs.getString(1);
    if(pwd.equals(pass)){
        this.dispose();
        DASHBOARD.setVisible(true);
    }
    else{
    JOptionPane.showMessageDialog(null, "See, your userID or password is wrong. Try again!");
    }
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        REGISTER.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CARRENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARRENTActionPerformed
  String ca="no";
     try{
     con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
      stmt = con.createStatement();
      String sql = "SELECT car FROM user WHERE uname= '" + uid + "';";
     System.out.println(sql);
     rs = stmt.executeQuery(sql);
      rs.first();
     String car = rs.getString(1);
    if(ca.equals(car)){
        this.dispose();
        RENT.setVisible(true);
    }
    else{
    JOptionPane.showMessageDialog(null, "sorry but our servies are not avilable for you as you have not retured the car");
    }
    }
   catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_CARRENTActionPerformed

    private void OFFFERSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFFERSActionPerformed
        DASHBOARD.dispose();
        SPECIAL.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_OFFFERSActionPerformed

    private void ENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENDActionPerformed
        DASHBOARD.dispose();
        FINAL.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ENDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DASHBOARD.dispose();
        PROFILE.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DASHBOARD.dispose();
        ABOUTUS.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       DASHBOARD.dispose();
       new NewJFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        RENT.dispose();
        DASHBOARD.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        totalLabel.setText("");
        guideLabel.setText("");
        finaltotalLabel.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void finaltotalLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finaltotalLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finaltotalLabelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int[] carCost = new int[]{ 1,2,3,4,5,6,7,8,9,10 };
        int total=0;
        int days=Integer.parseInt(jTextField1.getText());
        int guide=0;
        if(drivercheckbox.isSelected())
        {
            guide=500*days;
        }
        int carindex = cars.getSelectedIndex();
        Object nameOfcar = cars.getSelectedItem();
        total = carCost[carindex]*days;
        amount =total+guide;
        rateLabel.setText("" + carCost[carindex]);
        totalLabel.setText("" + total);
        guideLabel.setText("" + guide);
        finaltotalLabel.setText("" + amount);
         disLabel.setText("" + pa);
         amount=amount-pa;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String ca="ya";
 try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
        String sql = "update user set AMO = " + amount + ", bookdate= curdate(), car =' " +ca+ " ' where uname='"+uid+"';";
        System.out.println(sql);
        stmt.executeUpdate(sql);
        stmt.close();
         con.close();
         JOptionPane.showMessageDialog(rootPane, "Congrats! you have successfully booked the car");
}
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void userTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF1ActionPerformed
          cont.requestFocus();
}//GEN-LAST:event_userTF1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String name = nameTF.getText();
        uid = userTF1.getText();
        String pwd = new String(PF1.getPassword());
        String car ="no";
        String contact = cont.getText();
        String adddress = add.getText();
try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt = con.createStatement();
    String sql = "INSERT INTO User(name, uname, Pass,doj ,car,contact,address) VALUES('" + name + "', '" + uid + "', '" + pwd + "', curdate(),'" + car + "','" + contact + "','" + adddress + "');";
    System.out.println(sql);
    stmt.executeUpdate(sql);
    JOptionPane.showMessageDialog(rootPane, "Congrats! Account created successfully!");
    REGISTER.dispose();
    DASHBOARD.setVisible(true);
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        String u = jTextField4.getText();
      String p = new String(PASSWORDLABEL.getPassword());
      String ca="no";
      int amou=0;
      try{
    con1 =    DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt1 =  (Statement) con1.createStatement();
    String sql1 = "SELECT Pass FROM employee WHERE uname= '" + u + "';";
    System.out.println(sql1);
    rs = stmt1.executeQuery(sql1);
    rs.first();
    String pass = rs.getString(1);
    if(p.equals(pass)){
         try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
        String sql = "update user set AMO = " + amou + ", givedate= curdate(), car ='"+ca+"',rides = rides + 1 where uname='"+uid+"';";
        System.out.println(sql);
        stmt.executeUpdate(sql);
         stmt.close();
         con.close();
         JOptionPane.showMessageDialog(rootPane, "Congrats! you have successfully returned the car");
            }
         catch(Exception e1){
       JOptionPane.showMessageDialog(null, e1.getMessage());
           }
         stmt1.close();
         con1.close();
         rs.close();
    }
    else{
    JOptionPane.showMessageDialog(null, "it is for our employees only");
    }

      }
      catch(Exception e2){
    JOptionPane.showMessageDialog(null, e2.getMessage());
    }//GEN-LAST:event_RETURNActionPerformed
    }
    @SuppressWarnings("empty-statement")
    private void FINALWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FINALWindowActivated

         try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt = con.createStatement();
    String sql = "SELECT * FROM user WHERE uname = '" + uid + "';";
    rs = stmt.executeQuery(sql);
    rs.first();
    AMOUNTLABEL.setText(""+rs.getInt("amo"));
    DATE.setText(rs.getString("bookdate"));
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
}//GEN-LAST:event_FINALWindowActivated

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
               this.dispose();
               DASHBOARD.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void PROFILEWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PROFILEWindowActivated
            try{
    con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt = con.createStatement();
    String sql = "SELECT * FROM USER WHERE uname = '" + uid + "';";
    rs = stmt.executeQuery(sql);
    rs.first();
   jTextField2.setText(rs.getString("name"));
    uname.setText(rs.getString("uname"));
     address.setText(rs.getString("address"));
      contact.setText(rs.getString("contact"));
       bookdate.setText(rs.getString("bookdate"));
        pass.setText(rs.getString("pass"));
         car.setText(rs.getString("car"));

    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}    // TODO add your handling code here:
    }//GEN-LAST:event_PROFILEWindowActivated

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      PROFILE.dispose();
      DASHBOARD.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
          String name = JOptionPane.showInputDialog(null, "Enter the new name here:");
          try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
         String sql = "update user set name =' " +name+ " ' where uname='"+uid+"';";
         System.out.println(sql);
         stmt.executeUpdate(sql);
         stmt.close();
         con.close();
          }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
           String name = JOptionPane.showInputDialog(null, "Enter the new address here:");
          try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
         String sql = "update user set address =' " +name+ " ' where uname='"+uid+"';";
         System.out.println(sql);
         stmt.executeUpdate(sql);
         stmt.close();
         con.close();
          }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
          String name = JOptionPane.showInputDialog(null, "Enter the new contact no. here:");
          try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
         String sql = "update user set contact =' " +name+ " ' where uname='"+uid+"';";
         System.out.println(sql);
         stmt.executeUpdate(sql);
         stmt.close();
         con.close();
          }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }
    }//GEN-LAST:event_contactActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void SPECIALWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SPECIALWindowActivated
   // TODO add your handling code here:
    }//GEN-LAST:event_SPECIALWindowActivated

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 String c = jTextField3.getText();

    int pa=0;
    int ga=0;
      try{
    con =    DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt =  (Statement) con.createStatement();
    String sql = "SELECT discount FROM codes WHERE code= '" + c + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
     pa = rs.getInt(1);
     rs.close();
    stmt.close();
    con.close();
     }
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
     try{
    con =    DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt =  (Statement) con.createStatement();
    String sql = "SELECT discount FROM USER WHERE uname= '" + uid + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
     ga = rs.getInt(1);
     rs.close();
    stmt.close();
    con.close();
     }
catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    if(ga==0){
 try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
         String sql1 = "update user set discount = discount + "+ pa +"  where uname='"+uid+"';";
         System.out.println(sql1);
         stmt.executeUpdate(sql1);
         stmt.close();
         con.close();
         JOptionPane.showMessageDialog(rootPane, "OFFER APPLIED PROCEED TO BOOK YOUR CAR ");
          }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }}
    else{
             JOptionPane.showMessageDialog(rootPane, "OFFERS ARE ALREADY APPLIED ");
    }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void RENTWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RENTWindowActivated

        try{
    con =    DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
    stmt =  (Statement) con.createStatement();
    String sql = "SELECT discount FROM user WHERE uname= '" + uid + "';";
    System.out.println(sql);
    rs = stmt.executeQuery(sql);
    rs.first();
    pa = rs.getInt(1);
     rs.close();
    stmt.close();
    con.close();
     }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }
    }//GEN-LAST:event_RENTWindowActivated

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 tm=(DefaultTableModel) table1.getModel();
 tm.setRowCount(0);
        try
{         con = DriverManager.getConnection("jdbc:mysql://localhost/dbjava", "root", "1234");
         stmt = con.createStatement();
         String sql = "select * from codes WHERE EXP > CURDATE;";
         System.out.println(sql);
         rs=stmt.executeQuery(sql);
while(rs.next())
{
      tm.addRow( new Object [] {rs.getString("code"),rs.getString("des"),rs.getInt("discount")});
}
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,e);
}            // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        SPECIAL.dispose();
        DASHBOARD.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void userTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF2ActionPerformed
        PF2.requestFocus();
    }//GEN-LAST:event_userTF2ActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
          userTF1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
            add.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_contActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
             PF1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed
    
   /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ABOUTUS;
    private javax.swing.JTextField AMOUNTLABEL;
    private javax.swing.JButton CARRENT;
    private javax.swing.JFrame DASHBOARD;
    private javax.swing.JTextField DATE;
    private javax.swing.JButton END;
    private javax.swing.JFrame FINAL;
    private javax.swing.JButton OFFFERS;
    private javax.swing.JPasswordField PASSWORDLABEL;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JFrame PROFILE;
    private javax.swing.JFrame REGISTER;
    private javax.swing.JFrame RENT;
    private javax.swing.JButton RETURN;
    private javax.swing.JFrame SPECIAL;
    private javax.swing.JTextField add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField bookdate;
    private javax.swing.JTextField car;
    private javax.swing.JComboBox cars;
    private javax.swing.JTextField cont;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField disLabel;
    private javax.swing.JCheckBox drivercheckbox;
    private javax.swing.JTextField finaltotalLabel;
    private javax.swing.JTextField guideLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField rateLabel;
    private javax.swing.JTable table1;
    private javax.swing.JTextField totalLabel;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField userTF1;
    private javax.swing.JTextField userTF2;
    // End of variables declaration//GEN-END:variables

}
